import { TemplateData } from '@/lib/types';

export const postTemplates: TemplateData = {
  templates: {
    Low: [
      "What if we replaced {startup} with {comparison}? Just think about it.",
      "I've been thinking: {buzzword} is just {comparison} but for techies.",
      "Hot take: The next big thing isn't {ai}, it's actually {comparison}.",
      "If you're not using {buzzword} in your workflow, you're missing out on 80% productivity gains.",
      "The problem with most {startup} companies is they forget the fundamentals of {comparison}.",
      "India doesn't need more {iit} graduates, it needs more people who understand {comparison}.",
      "Friendly reminder: You don't need {hustle} to succeed. You need {comparison}.",
      "Sunday thought: What if {crypto} was actually designed like {comparison}?",
      "Unpopular opinion: {buzzword} is overrated. We should focus more on {comparison}.",
      "I'm convinced that {ai} will transform {startup} the same way smartphones transformed communication."
    ],
    Medium: [
      "Indian startups be like: Burn ₹10 Cr, raise ₹100 Cr, call it {buzzword}, and still ask for government subsidies.",
      "{iit} grads on LinkedIn be like: 'Rejected Google and Microsoft to join this pre-seed {startup} because {hustle}'",
      "Bengaluru developers be like: 'My {ai} algorithm is revolutionary' My brother in Christ, it's just nested if-else statements.",
      "Every founder pitch: 'We're building {buzzword} for {comparison}' Translation: 'We have no idea what we're doing but please give us money'",
      "Tech bros posting daily: '5 AM club ✅ Cold shower ✅ 2-hour workout ✅' But can't code a simple for loop without StackOverflow.",
      "Indians on Twitter claiming to build the next {crypto} revolution while their servers crash if more than 10 users log in simultaneously.",
      "{bro} culture has tech folks believing they're changing the world when they're really just making another app to order chai faster.",
      "VCs throwing $10M at some random guy from {iit} who promises {buzzword} but delivers a WordPress site with custom CSS.",
      "Indian parents be like: 'Beta, {startup} chhodo, become SDC-XIX at FAANG with 75 LPA'",
      "'We're disrupting {startup} with cutting-edge {ai}' = We added a dropdown menu and some if-else statements."
    ],
    High: [
      "If you're 24, not a founder, and still coding — congrats, you're officially a NPC. Touch VC deck. Smell pitch. Hustle harder.",
      "Indians on LinkedIn be like: Rejected ₹4 CR Google package to join {startup} for ₹12 LPA because 'learning opportunity' and 'EsOps'. Bhai, sach bol, tu select hi nahi hua.",
      "Your {ai} startup isn't failing because of the market. It's failing because you spent 6 months on the logo and your code is garbage. But sure, blame 'funding winter'.",
      "Tech Twitter during layoffs: 'Feeling for all affected 🙏🏼' Same Tech Twitter during hiring: 'Sorry, we only hire IIT/IIM with 10 YOE willing to work for junior salary who can also make chai.'",
      "Working 18 hours a day for your 'revolutionary' {startup} making another food delivery app, only to sell it to Swiggy for pennies on the dollar in 2 years. Sigma grindset achieved! 💪",
      "Bro spending 6 hours daily on Twitter, posting about {hustle} and {buzzword}, while his actual startup is just a Figma mockup he made 8 months ago.",
      "Your entire personality is {crypto}, {hustle}, and how you wake up at 4:30 AM. We get it, you're compensating for having the charisma of a wet cardboard box.",
      "Congrats on raising your Series A for your 'AI-driven' startup that's actually just 12 if-statements and a UI stolen from Dribbble. BHARAT INNOVATING! 🇮🇳",
      "Every 'tech influencer' from {iit}: Copy tweets from Americans, add 'for Indian ecosystem', get 500 likes from equally delusional followers. Rinse, repeat, build 'personal brand'.",
      "'Hard pills to swallow: 99% of {startup} founders are just privileged kids with rich parents who call themselves 'self-made' after burning daddy's money and getting lucky once."
    ]
  },
  phrases: {
    startup: [
      "early-stage startups",
      "10X unicorns",
      "bootstrapped SaaS",
      "Flipkart mafia",
      "Ola/Uber for X",
      "Shark Tank rejects",
      "pre-seed ventures",
      "'Airbnb for pets'",
      "Swiggy/Zomato clones",
      "B2B fintech",
      "D2C brands",
      "edtech unicorns",
      "BYJU's competitors",
      "Zerodha copycats",
      "Paytm wannabes",
      "OYO in different verticals"
    ],
    iit: [
      "IIT/IIM grads",
      "GATE toppers",
      "JEE Advanced AIR 1",
      "campus placement heroes",
      "UPSC aspirants",
      "CAT 99.9 percentilers",
      "coaching center products",
      "Kota factory alumni",
      "Stanford-returned founders",
      "6-pointer IITians",
      "Tier-1 college elitists",
      "NIT/BITS graduates",
      "IIT Kanpur CS branch",
      "IIM Ahmedabad finance bros"
    ],
    ai: [
      "GPT-4 fine-tuning",
      "AI prompt engineering",
      "computer vision models",
      "sentient chatbots",
      "machine learning pipelines",
      "generative AI",
      "AI-powered recommendations",
      "neural networks",
      "deep learning",
      "transformer models",
      "LLM hallucinations",
      "CV/NLP hybrid models",
      "AI for vernacular languages",
      "OpenAI competitors"
    ],
    crypto: [
      "Web3 evangelists",
      "crypto moonboys",
      "NFT collectors",
      "Ethereum dapps",
      "metaverse land",
      "blockchain solutions",
      "DeFi protocols",
      "smart contracts",
      "token engineering",
      "crypto winter survivors",
      "Bitcoin maxis",
      "altcoin sorcerers",
      "crypto regulations",
      "DAO governance"
    ],
    hustle: [
      "9-9-6 culture",
      "rise & grind mentality",
      "side-hustle millionaires",
      "72-hour work weeks",
      "cold shower disciples",
      "4AM club devotees",
      "Kindle highlights posters",
      "LinkedIn motivation merchants",
      "hustle porn addicts",
      "productivity app junkies",
      "passion economy workers",
      "freelance empire builders"
    ],
    bro: [
      "tech bros",
      "finance chads",
      "sigma males",
      "alpha mentality",
      "gymbros giving VC advice",
      "networking ninjas",
      "startup rockstars",
      "LinkedIn lunatics",
      "community builders",
      "thought leaders",
      "growth hackers",
      "personal brand gurus"
    ],
    hinglish: [
      "Bhai, yeh mind-blowing hai!",
      "Ekdum next level!",
      "Abhi toh party shuru hui hai",
      "Founders ka time aa gaya hai",
      "Coding karo, ladki baad mein pat jayegi",
      "Kya baat hai bhai",
      "Bilkul sahi pakde hain",
      "Kahan se late ho ye ideas",
      "Ye to apna hi kaam hai",
      "Funding mil gayi? Badhiya hai!",
      "Sab changa si",
      "Aur batao, kaisa chal raha hai startup?",
      "Apna time aayega",
      "Yaar, mujhe funding nahi product-market fit chahiye",
      "Bas kar pagle, rulayega kya?"
    ]
  },
  comparisons: [
    "a glorified Excel sheet",
    "Notepad with extra steps",
    "desi jugaad",
    "MS Paint with AI",
    "WhatsApp group gone wrong",
    "your mom's Facebook feed",
    "a fancy to-do list",
    "Chai pe charcha with PPT",
    "college mini-project",
    "Google Form with attitude",
    "Instagram but for lonely devs",
    "LinkedIn premium features",
    "Ola but for coding problems",
    "Zomato for useless gadgets",
    "IRCTC with better UI",
    "a fancy Slack channel",
    "LIC policy with tech branding",
    "YouTube tutorials monetized",
    "StayUncle for algorithms"
  ],
  buzzwords: [
    "AI/ML",
    "Web3",
    "Quantum computing",
    "DevSecOps",
    "LLMOps",
    "Microservices",
    "Cloud-native",
    "Serverless",
    "DataOps",
    "RAG architecture",
    "Frictionless UX",
    "GenAI",
    "Edge computing",
    "Internet of Behaviors",
    "FinOps",
    "Zero Trust",
    "Digital Twin",
    "MLOps",
    "Hyperautomation",
    "Distributed ledger",
    "Smart contracts",
    "Computer vision",
    "NLP-powered",
    "Full-stack AI"
  ],
  authors: [
    { name: "Aryan Sharma", handle: "@AryanSharma.io" },
    { name: "Vikram Ventures", handle: "@TheVikramVC" },
    { name: "Aarav Patel", handle: "@AaravBuilds" },
    { name: "Ananya Mehta", handle: "@AnanyaTechBoss" },
    { name: "Rajesh Gupta", handle: "@10xRajesh" },
    { name: "Riya Singh", handle: "@RiyaInTech" },
    { name: "Rahul Founder", handle: "@RahulFounderAI" },
    { name: "Vishal Shah", handle: "@BLRTechBro" },
    { name: "Naina Kapoor", handle: "@NainaDecodesLife" },
    { name: "Dev Sharma", handle: "@DevStartupGuru" },
    { name: "Isha Joshi", handle: "@IshaJoshiAI" },
    { name: "Prakash Coder", handle: "@PrakashWakeUpAt4" },
    { name: "Sara Singh", handle: "@SaraQuitsMNC" },
    { name: "Karan Mehra", handle: "@KaranMehraIIT" },
    { name: "Priya Patel", handle: "@PriyaVCFund" },
    { name: "Amit Kumar", handle: "@AmitExIITIIM" },
    { name: "Neha Sharma", handle: "@NehaCryptoQueen" },
    { name: "Vivek Chawla", handle: "@VivekBuildsInPublic" },
    { name: "Tanvi Mehta", handle: "@TanviMehtaProduct" },
    { name: "Rohit Reddy", handle: "@RohitReddyHustles" }
  ]
};